{
	"schema_version": "1.6.0",
	"id": "CVE-2023-43788",
	"modified": "2024-09-02T01:16:21.907823Z",
	"published": "2023-10-10T13:15:22Z",
	"related": [
		"ALSA-2024:2146",
		"ALSA-2024:2217",
		"ALSA-2024:2974",
		"ALSA-2024:3022",
		"DLA-3603-1",
		"DSA-5516-1",
		"RLSA-2024:2974",
		"USN-6408-1",
		"USN-6408-2"
	],
	"details": "A vulnerability was found in libXpm due to a boundary condition within the XpmCreateXpmImageFromBuffer() function. This flaw allows a local attacker to trigger an out-of-bounds read error and read the contents of memory on the system.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Alpine:v3.19",
				"name": "libxpm",
				"purl": "pkg:apk/alpine/libxpm?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.5.17-r0"
						}
					]
				}
			],
			"versions": [
				"3.5.10-r0",
				"3.5.11-r0",
				"3.5.11-r1",
				"3.5.12-r0",
				"3.5.13-r0",
				"3.5.13-r1",
				"3.5.14-r0",
				"3.5.15-r0",
				"3.5.15-r1",
				"3.5.15-r2",
				"3.5.16-r0",
				"3.5.16-r1",
				"3.5.7-r0",
				"3.5.8-r0",
				"3.5.8-r1",
				"3.5.8-r2",
				"3.5.8-r3",
				"3.5.8-r4",
				"3.5.9-r0",
				"3.5.9-r1",
				"3.5.9-r2",
				"3.5.9-r3"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-43788.json"
			}
		},
		{
			"package": {
				"ecosystem": "Alpine:v3.20",
				"name": "libxpm",
				"purl": "pkg:apk/alpine/libxpm?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.5.17-r0"
						}
					]
				}
			],
			"versions": [
				"3.5.10-r0",
				"3.5.11-r0",
				"3.5.11-r1",
				"3.5.12-r0",
				"3.5.13-r0",
				"3.5.13-r1",
				"3.5.14-r0",
				"3.5.15-r0",
				"3.5.15-r1",
				"3.5.15-r2",
				"3.5.16-r0",
				"3.5.16-r1",
				"3.5.7-r0",
				"3.5.8-r0",
				"3.5.8-r1",
				"3.5.8-r2",
				"3.5.8-r3",
				"3.5.8-r4",
				"3.5.9-r0",
				"3.5.9-r1",
				"3.5.9-r2",
				"3.5.9-r3"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-43788.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:2146"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:2217"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:2974"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:3022"
		},
		{
			"type": "ARTICLE",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/63IBRFLQVZSMOAZBZOBKFWJP26ILRAGQ/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3KFUQT42R7TB4D7RISNSBQFJGLTQGUL/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TFAJTBNO3PAIA6EGZR4PN62H6RLKNDTE/"
		},
		{
			"type": "ARTICLE",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/V6FARGWN7VWXXWPXYNEEDJLRR3EWFZ3T/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZECBCLDYUGLDSVV75ECPIBW7JXOB3747/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2242248"
		},
		{
			"type": "WEB",
			"url": "https://access.redhat.com/security/cve/CVE-2023-43788"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.alpinelinux.org/vuln/CVE-2023-43788"
		}
	]
}
